### ISSUE TITLE
PASCAL-VOC format

### ISSUE THREAD

**Issue by csterling** [waikato-ufdl/wai-annotations#10]
Add the [PASCAL-VOC](http://host.robots.ox.ac.uk/pascal/VOC/) format

**Comment by csterling** [comment]
Input format implemented in [this release](https://github.com/waikato-ufdl/wai-annotations-voc/releases/tag/v1.0.0).

Output format still to-do.

**Comment by fracpete** [comment]
available through https://github.com/waikato-ufdl/wai-annotations-voc
