### ISSUE TITLE
Auto-generate stage documentation

### ISSUE THREAD

**Issue by csterling** [waikato-ufdl/wai-annotations#15]
By running wai.annotations with the `--list-plugins` option, the user can see what options are available to them.

It would be useful to include this information in the documentation as well.

Make running this command and automatically updating the documentation part of wai.annotations' release process.

**Comment by fracpete** [comment]
This is mentioned in the release documentation: https://github.com/waikato-ufdl/wai-annotations/blob/master/RELEASE.md
