### ISSUE TITLE
Add image segmentation domain

### ISSUE THREAD

**Issue by csterling** [waikato-ufdl/wai-annotations#25]
Add a domain for image segmentation, where every pixel is classified by a label (or, if unclassified, is considered part of the "background" label).

See [this Google Drive folder](https://drive.google.com/drive/folders/1t3ZjkbPJsnBzE1kIyAbHu40G2vf-FtVd?usp=sharing) for an example data-set in two formats (indexed PNG, blue-channel PNG) and a link to conversion code between the two.

**Comment by csterling** [comment]
@fracpete Looking at the example data-sets, there doesn't seem to be a definition of what labels the different indices/blue-channel values correspond to. Is this normal for image-segmentation data-sets?

**Comment by fracpete** [comment]
From what little I know, this seems to be the case. The code using the segmentation model is supposed to know what indices correspond to what label. Maybe worth asking Dale as well.

**Comment by csterling** [comment]
Notes from meeting with @fracpete:
- As the indexed-PNG/blue-channel formats don't define a mapping from indices to labels, the readers for `wai.annotations` for these formats will require that the labels are specified via parameter.
- Also introduce a new format, which stores a separate image per label, which is a binary mask of the pixels that correspond to that label.
- The filenames for the label images will be `{basename}-{label}.png`, with the separator being variable for when filenames use a dash already.
- As this format will introduce the possibility of overlap of classifications, add a parameter to specify a priority for reducing the overlap to a single label.
- Add a parameter to specify the directory where to find the data images, given the location of the annotation image/s.

**Comment by fracpete** [comment]
Allow bounding box/shape annotations from the object detection domain be converted into image segmentation annotations.

**Comment by csterling** [comment]
All features mentioned in this issue are implemented as of ecc448938504030821823d7f568d3d8e419a1dcd / [v0.5.2](https://github.com/waikato-ufdl/wai-annotations/releases/tag/v0.5.2)
