### ISSUE TITLE
COCO output sort labels

### ISSUE THREAD

**Issue by fracpete** [waikato-ufdl/wai-annotations#3]
* ensure order of categories in COCO JSON file by sorting the labels

**Comment by csterling** [comment]
This is implemented in commit ad35098583ba72ca62af86719e0aa978e84ed42c and released in [v0.4.2](https://github.com/waikato-ufdl/wai-annotations/releases/tag/v0.4.2).

**Comment by csterling** [comment]
Commit 83f672dcb1d27efd2ddc1a513bd5e444973bacbd meets the original specification of this issue, allowing the categories to be sorted alphabetically. This functionality was included in release [v0.4.3](https://github.com/waikato-ufdl/wai-annotations/releases/tag/v0.4.3).
