### ISSUE TITLE
Check version requirement for numpy

### ISSUE THREAD

**Issue by fracpete** [waikato-ufdl/wai-annotations#35]
At the moment, the numpy version is fixed to the following range:
```
numpy>=1.16,<=1.17.4
```
However, this clashes with other modules used by UFDL projects (and pip 20.3 requires ` --use-deprecated=legacy-resolver` flag to succeed).

Check whether this requirement is still necessary:
- from ADAMS annotations create two tfrecords datasets (one with older version and one with current version of numpy)
- reconvert the tfrecords datasets than back into ADAMS annotations and compare the two (old/current numpy version)
- if no difference, remove restriction

**Comment by csterling** [comment]
Implemented in a386d10292b8ac656aa16f4db69c47ecfd5d6fcc
