### ISSUE TITLE
Add URL to format specifications to format plugin descriptions

### ISSUE THREAD

**Issue by csterling** [waikato-ufdl/wai-annotations#4]
These were in the README in the previous version ([v0.3.6](https://github.com/waikato-ufdl/wai-annotations/releases/tag/v0.3.6))
* ROI has no website, link to a document specifying the format
* ADAMS should have link to website and a document specifying the format

**Comment by csterling** [comment]
@fracpete These format-specification documents, where should they live?

**Comment by fracpete** [comment]
Just create markdown files for each of the formats and place the files in `doc/formats`.

**Comment by fracpete** [comment]
Added information with https://github.com/waikato-ufdl/wai-annotations-roi/commit/62f4ae7359cef489e93f7a117fb0cd9ac98b688c and https://github.com/waikato-ufdl/wai-annotations-adams/commit/b12a6ca439fe0cb9c8b9dee348344b41ead56379
