### ISSUE TITLE
UFDL formats

### ISSUE THREAD

**Issue by csterling** [waikato-ufdl/wai-annotations#8]
Add input/output formats which source their data from a UFDL server.

**Comment by csterling** [comment]
@fracpete can you create a new repo for this? Because it will depend on wai.annotations and ufdl-python-client, if it's added to one of the existing packages it will introduce another dependency. Since this is what the plugin system is designed for, best to make it an external plugin for wai.annotations.

How about `ufdl-annotations-plugin`?

**Comment by fracpete** [comment]
The repo https://github.com/waikato-ufdl/ufdl-annotations-plugin is now available.

**Comment by csterling** [comment]
Closed as this issue has been moved to the new [repo](https://github.com/waikato-ufdl/ufdl-annotations-plugin)
